apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    controller:
      enabled: true
    speaker:
      enabled: true
      # 1. Run ONLY on Edge Nodes
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      # 2. Tolerate the 'NoSchedule' taint so it can actually start there
      tolerations:
        - key: "node-role.kubernetes.io/edge"
          operator: "Exists"
          effect: "NoSchedule"
