apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 12h
  targetNamespace: metallb-system
  install:
    createNamespace: true
  values:
    # Minimal config to get it running
    speaker:
      tolerateMaster: true
