creation_rules:
  # 1. Specific Rule for Talos Files
  - path_regex: "^(.*.yaml|talosconfig)$"
    encrypted_regex: '(?i)(key|crt|token|secret|ca|id|password)$'
    age: "age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua"
